changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: Security
      labels:
        - security
    - title: Features
      labels:
        - feature
        - enhancement
        - semver-minor
    - title: Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Dependencies
      labels:
        - dependencies
        - dependency
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - '*'